services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MODE: "survival"
      PVP: "true"
      SERVER_NAME: "TabernaPlay"
      DIFFICULTY: "hard"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  data: {}
